version: 0.2
phases:
  install: 
    commands:
      - apt-get update -y
      - apt-get install -y jq
      - pip install awscli --upgrade --user
      - cd ${CODEBUILD_SRC_DIR}/scripts/modules/pipeline-creation && npm install
  build:
    commands:
      - mkdir -p ${CODEBUILD_SRC_DIR}/output
      # Package main infrastructure
      - bash ${CODEBUILD_SRC_DIR}/scripts/package.sh
      - mv ${CODEBUILD_SRC_DIR}/infra/cloudformation.pkg.yaml output/main.yaml
      # Package core modules
      - bash ${CODEBUILD_SRC_DIR}/scripts/modules/build-all.sh $CORE_MODULES
      # Package modules
      - bash ${CODEBUILD_SRC_DIR}/scripts/modules/build-all.sh $INSTALLED_MODULES
      # Create module pipeline definition
      - node ${CODEBUILD_SRC_DIR}/scripts/modules/pipeline-creation/index.js
artifacts:
  files:
    - output
  discard-paths: yes