AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Provides the system with centralized logging tools, that can be thereafter used for logging purposes.
Resources:
  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
  LoggingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LoggingBucket
      PolicyDocument:
        Statement: 
          - 
            Sid: "CWLAccess"
            Action: 
              - "s3:GetBucketAcl"
              - "s3:PutObject"
            Effect: Allow
            Resource: 
              - !Sub "arn:aws:s3:::${LoggingBucket}"
              - !Sub "arn:aws:s3:::${LoggingBucket}/*"
            Principal: 
              Service:
                - !Sub "logs.${AWS::Region}.amazonaws.com"
          - 
            Sid: "CloudTrailACLCheck"
            Action: 
              - "s3:GetBucketAcl"
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Resource:
              - !GetAtt LoggingBucket.Arn
          - 
            Sid: "CloudTrailWrite"
            Action: 
              - s3:PutObject
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Resource: 
              - !Sub ${LoggingBucket.Arn}/trail/*
            Condition:
              StringEquals: 
                s3:x-amz-acl: bucket-owner-full-control

Outputs:
  LoggingBucketName:
    Description: Name of the bucket used for storing logs
    Value: !Ref LoggingBucket
    Export:
      Name: connected-vehicle-logging-bucket