AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  OAuthToken:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Token used to fetch code from Gitub
    Default: GITHUB_OAUTH_TOKEN
    NoEcho: True
Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location:
          Fn::ImportValue: connected-vehicle-cicd-artifacts-bucket
        Type: S3
      DisableInboundStageTransitions: []
      Name: ConnectedVehicleModules
      RoleArn:
        Fn::GetAtt: PipelineRole.Arn
      Stages:
        - 
          Name: Source
          Actions:
            -
              Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                PollForSourceChanges: false
                S3Bucket: 
                  Fn::ImportValue: connected-vehicle-cicd-artifacts-bucket
                S3ObjectKey: core/system/module-definition.zip
              OutputArtifacts:
                - Name: SourceCode
              RunOrder: 1
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "codepipeline.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Policies:
        - 
          PolicyName: "AllStages"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Sid: "ManageArtifacts"
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                Effect: "Allow"
                Resource:
                  Fn::Sub: 
                    - "arn:aws:s3:::${ArtifactsBucket}/*"
                    -  
                      ArtifactsBucket: 
                        Fn::ImportValue: connected-vehicle-cicd-artifacts-bucket
              - 
                Sid: "PassRole"
                Action:
                  - "iam:PassRole"
                Effect: "Allow"
                Resource: "*"
              - 
                Sid: "PublishSNS"
                Action:
                  - "sns:Publish"
                Effect: "Allow"
                Resource: "*"
        - 
          PolicyName: "SourceStage"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Sid: "ReadRepository"
                Action:
                  - "codecommit:GetBranch"
                  - "codecommit:GetCommit"
                  - "codecommit:UploadArchive"
                  - "codecommit:GetUploadArchiveStatus"
                  - "codecommit:CancelUploadArchive"
                Effect: "Allow"
                Resource: "*"
        - 
          PolicyName: "DeployStage"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Sid: "CloudFormationManagement"
                Action:
                  - "cloudformation:CreateChangeSet"
                  - "cloudformation:DeleteChangeSet"
                  - "cloudformation:DescribeChangeSet"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:ExecuteChangeSet"
                Effect: "Allow"
                Resource: "*"
        - 
          PolicyName: "CloudWatchLogs"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Sid: "WriteLogs"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Effect: "Allow"
                Resource: "*"
  PipelineDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "cloudformation.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Policies:
        - 
          PolicyName: "AdministratorAccess"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Sid: "AdministratorAccess"
                Action: "*"
                Effect: "Allow"
                Resource: "*"
  PipelineTrail:
    Type: "AWS::CloudTrail::Trail"
    Properties:
      EventSelectors:
        - 
          DataResources: 
            - 
              Type: AWS::S3::Object
              Values: 
                - 
                  Fn::Sub:
                    - "arn:aws:s3:::${BucketName}/${ObjectKey}"
                    - 
                      BucketName: 
                        Fn::ImportValue: connected-vehicle-cicd-artifacts-bucket
                      ObjectKey: core/system/module-definition.zip
                
          IncludeManagementEvents: false
          ReadWriteType: WriteOnly
      IsLogging: true
      IsMultiRegionTrail: false
      KMSKeyId: String
      S3BucketName: 
        Fn::ImportValue: connected-vehicle-logging-bucket
      S3KeyPrefix: trail/
  PipelineTrigger:
    Type: AWS::Events::Rule
    Properties: 
      Description: Triggers the execution of the pipeline upon source changes
      EventPattern: 
        source:
          - "aws.s3"
        detail-type: 
          - AWS API Call via CloudTrail
        detail:
          eventSource: 
            - s3.amazonaws.com
          eventName: 
            - PutObject
          resources: 
            ARN:
              - Fn::Sub: 
                - "arn:aws:s3:::${ArtifactsBucket}/core/system/module-definition.zip"
                -  
                  ArtifactsBucket: 
                    Fn::ImportValue: connected-vehicle-cicd-artifacts-bucket

      Name: ModulesPipelineTrigger
      State: ENABLED
      Targets:
        - 
          Id: CodePipeline1
          Arn: 
            Fn::Sub: "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${Pipeline}"
          RoleArn: 
            Fn::GetAtt: PipelineTriggerRole.Arn
  PipelineTriggerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "events.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Policies:
        - 
          PolicyName: "CloudWatchLogs"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Sid: "WriteLogs"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Effect: "Allow"
                Resource: "*"
        - 
          PolicyName: PipelineManagement
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - 
                Sid: "StartPipeline"
                Action: 
                  - "codepipeline:StartExecution"
                Effect: Allow
                Resource: 
                  - Fn::Sub: "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${Pipeline}"